FROM mongo

# This step is optional if you want to import data into the MongoDB container during setup.
COPY C:/Users/ayesha.amjad/Documents/GitHub/BigDataProject/MLOPS/Project/archive/ChurnData.json
CMD mongoimport --host MainMongoDB --db  --collection churn --type json --file C:/Users/ayesha.amjad/Documents/GitHub/BigDataProject/MLOPS/Project/archive/ChurnData.json --jsonArray
